
export const SET_GOOGLE_CREDENTIALS = 'SET_GOOGLE_CREDENTIALS';
export const START_LOADING = 'START_LOADING';
export const TRACKS_LOADED = 'TRACKS_LOADED';
export const FAILED_TO_LOAD = 'FAILED_TO_LOAD';
export const SELECT_TRACK = 'SELECT_TRACK';
export const NEXT_TRACK = 'NEXT_TRACK';
